// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources;

import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;

/**
 * Script Name   : <b>DOF</b><br>
 * Generated     : <b>2010/08/22 2:45:13</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows NT (unknown) x86 6.0 <br>
 * 
 * @since  °ËÔÂ 22, 2010
 * @author think
 */
public abstract class DOFHelper extends RationalTestScript
{
	

	protected DOFHelper()
	{
		setScriptName("DOF");
	}
	
}