// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources;
import HSC1;
import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;

/**
 * Script Name   : <b>Script2</b><br>
 * Generated     : <b>2010/10/03 13:01:05</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows NT (unknown) x86 6.0 <br>
 * 
 * @since  Ê®ÔÂ 03, 2010
 * @author think
 */
public abstract class Script2Helper extends HSC1
{
	/**
	 * _Finish£º with default state.
	 *		text : &Finish
	 * 		.class : org.eclipse.swt.widgets.Button
	 * 		.classIndex : 0
	 */
	protected GuiTestObject _Finish() 
	{
		return new GuiTestObject(
                        getMappedTestObject("_Finish"));
	}
	/**
	 * _Finish£º with specific test context and state.
	 *		text : &Finish
	 * 		.class : org.eclipse.swt.widgets.Button
	 * 		.classIndex : 0
	 */
	protected GuiTestObject _Finish(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("_Finish"), anchor, flags);
	}
	
	/**
	 * _Next£º with default state.
	 *		text : &Next >
	 * 		.class : org.eclipse.swt.widgets.Button
	 * 		.classIndex : 1
	 */
	protected GuiTestObject _Next() 
	{
		return new GuiTestObject(
                        getMappedTestObject("_Next"));
	}
	/**
	 * _Next£º with specific test context and state.
	 *		text : &Next >
	 * 		.class : org.eclipse.swt.widgets.Button
	 * 		.classIndex : 1
	 */
	protected GuiTestObject _Next(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("_Next"), anchor, flags);
	}
	
	/**
	 * New£º with default state.
	 *		.captionText : New
	 * 		.class : org.eclipse.swt.widgets.Shell
	 */
	protected TopLevelTestObject _new() 
	{
		return new TopLevelTestObject(
                        getMappedTestObject("_new"));
	}
	/**
	 * New£º with specific test context and state.
	 *		.captionText : New
	 * 		.class : org.eclipse.swt.widgets.Shell
	 */
	protected TopLevelTestObject _new(TestObject anchor, long flags) 
	{
		return new TopLevelTestObject(
                        getMappedTestObject("_new"), anchor, flags);
	}
	
	/**
	 * Menu£º with default state.
	 *		.class : org.eclipse.swt.widgets.Menu
	 */
	protected GuiSubitemTestObject menu() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("menu"));
	}
	/**
	 * Menu£º with specific test context and state.
	 *		.class : org.eclipse.swt.widgets.Menu
	 */
	protected GuiSubitemTestObject menu(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("menu"), anchor, flags);
	}
	
	/**
	 * NewSQLFile£º with default state.
	 *		.captionText : New SQL File
	 * 		.class : org.eclipse.swt.widgets.Shell
	 */
	protected TopLevelTestObject newSQLFile() 
	{
		return new TopLevelTestObject(
                        getMappedTestObject("newSQLFile"));
	}
	/**
	 * NewSQLFile£º with specific test context and state.
	 *		.captionText : New SQL File
	 * 		.class : org.eclipse.swt.widgets.Shell
	 */
	protected TopLevelTestObject newSQLFile(TestObject anchor, long flags) 
	{
		return new TopLevelTestObject(
                        getMappedTestObject("newSQLFile"), anchor, flags);
	}
	
	/**
	 * ServiceDevelopmentProject1Testfi£º with default state.
	 *		.captionText : Service Development - project1/testfile2.sql - Sybase WorkSpace
	 * 		.class : org.eclipse.swt.widgets.Shell
	 */
	protected TopLevelTestObject serviceDevelopmentProject1Test() 
	{
		return new TopLevelTestObject(
                        getMappedTestObject("serviceDevelopmentProject1Test"));
	}
	/**
	 * ServiceDevelopmentProject1Testfi£º with specific test context and state.
	 *		.captionText : Service Development - project1/testfile2.sql - Sybase WorkSpace
	 * 		.class : org.eclipse.swt.widgets.Shell
	 */
	protected TopLevelTestObject serviceDevelopmentProject1Test(TestObject anchor, long flags) 
	{
		return new TopLevelTestObject(
                        getMappedTestObject("serviceDevelopmentProject1Test"), anchor, flags);
	}
	
	/**
	 * Text£º with default state.
	 *		.class : org.eclipse.swt.widgets.Text
	 * 		.priorLabel : File name:
	 * 		.classIndex : 0
	 */
	protected TextScrollTestObject text() 
	{
		return new TextScrollTestObject(
                        getMappedTestObject("text"));
	}
	/**
	 * Text£º with specific test context and state.
	 *		.class : org.eclipse.swt.widgets.Text
	 * 		.priorLabel : File name:
	 * 		.classIndex : 0
	 */
	protected TextScrollTestObject text(TestObject anchor, long flags) 
	{
		return new TextScrollTestObject(
                        getMappedTestObject("text"), anchor, flags);
	}
	
	/**
	 * Tree£º with default state.
	 *		.class : org.eclipse.swt.widgets.Tree
	 * 		.classIndex : 0
	 */
	protected ScrollGuiSubitemTestObject tree() 
	{
		return new ScrollGuiSubitemTestObject(
                        getMappedTestObject("tree"));
	}
	/**
	 * Tree£º with specific test context and state.
	 *		.class : org.eclipse.swt.widgets.Tree
	 * 		.classIndex : 0
	 */
	protected ScrollGuiSubitemTestObject tree(TestObject anchor, long flags) 
	{
		return new ScrollGuiSubitemTestObject(
                        getMappedTestObject("tree"), anchor, flags);
	}
	
	

	protected Script2Helper()
	{
		setScriptName("Script2");
	}
	
}