// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources;
import HSC1;
import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;

/**
 * Script Name   : <b>Script1</b><br>
 * Generated     : <b>2010/09/03 17:32:47</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows NT (unknown) x86 6.0 <br>
 * 
 * @since  ¾ÅÔÂ 03, 2010
 * @author think
 */
public abstract class Script1Helper extends HSC1
{
	/**
	 * ContextMenu£º with default state.
	 *		.class : Java.PopupMenu
	 */
	protected GuiSubitemTestObject contextMenu() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("contextMenu"));
	}
	/**
	 * ContextMenu£º with specific test context and state.
	 *		.class : Java.PopupMenu
	 */
	protected GuiSubitemTestObject contextMenu(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("contextMenu"), anchor, flags);
	}
	
	/**
	 * OK£º with default state.
	 *		text : OK
	 * 		.class : org.eclipse.swt.widgets.Button
	 * 		.classIndex : 0
	 */
	protected GuiTestObject ok() 
	{
		return new GuiTestObject(
                        getMappedTestObject("ok"));
	}
	/**
	 * OK£º with specific test context and state.
	 *		text : OK
	 * 		.class : org.eclipse.swt.widgets.Button
	 * 		.classIndex : 0
	 */
	protected GuiTestObject ok(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("ok"), anchor, flags);
	}
	
	/**
	 * Text£º with default state.
	 *		.class : org.eclipse.swt.widgets.Text
	 * 		.priorLabel : Location:
	 * 		.classIndex : 2
	 */
	protected TextScrollTestObject text() 
	{
		return new TextScrollTestObject(
                        getMappedTestObject("text"));
	}
	/**
	 * Text£º with specific test context and state.
	 *		.class : org.eclipse.swt.widgets.Text
	 * 		.priorLabel : Location:
	 * 		.classIndex : 2
	 */
	protected TextScrollTestObject text(TestObject anchor, long flags) 
	{
		return new TextScrollTestObject(
                        getMappedTestObject("text"), anchor, flags);
	}
	
	/**
	 * Tree£º with default state.
	 *		.class : org.eclipse.swt.widgets.Tree
	 * 		.classIndex : 0
	 */
	protected ScrollGuiSubitemTestObject tree() 
	{
		return new ScrollGuiSubitemTestObject(
                        getMappedTestObject("tree"));
	}
	/**
	 * Tree£º with specific test context and state.
	 *		.class : org.eclipse.swt.widgets.Tree
	 * 		.classIndex : 0
	 */
	protected ScrollGuiSubitemTestObject tree(TestObject anchor, long flags) 
	{
		return new ScrollGuiSubitemTestObject(
                        getMappedTestObject("tree"), anchor, flags);
	}
	
	

	protected Script1Helper()
	{
		setScriptName("Script1");
	}
	
}