// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources;
import HSC1;
import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;

/**
 * Script Name   : <b>Script4</b><br>
 * Generated     : <b>2010/10/05 16:08:21</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows NT (unknown) x86 6.0 <br>
 * 
 * @since  Ê®ÔÂ 05, 2010
 * @author think
 */
public abstract class Script4Helper extends HSC1
{
	

	protected Script4Helper()
	{
		setScriptName("Script4");
	}
	
}