// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.sample;

import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;

/**
 * Script Name   : <b>Script2</b><br>
 * Generated     : <b>2010/10/05 17:50:38</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows NT (unknown) x86 6.0 <br>
 * 
 * @since  Ê®ÔÂ 05, 2010
 * @author think
 */
public abstract class Script2Helper extends RationalTestScript
{
	/**
	 * Cancel£º with default state.
	 *		text : Cancel
	 * 		.class : org.eclipse.swt.widgets.Button
	 * 		.classIndex : 1
	 */
	protected GuiTestObject cancel() 
	{
		return new GuiTestObject(
                        getMappedTestObject("cancel"));
	}
	/**
	 * Cancel£º with specific test context and state.
	 *		text : Cancel
	 * 		.class : org.eclipse.swt.widgets.Button
	 * 		.classIndex : 1
	 */
	protected GuiTestObject cancel(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("cancel"), anchor, flags);
	}
	
	/**
	 * ContextMenu£º with default state.
	 *		.class : Java.PopupMenu
	 */
	protected GuiSubitemTestObject contextMenu() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("contextMenu"));
	}
	/**
	 * ContextMenu£º with specific test context and state.
	 *		.class : Java.PopupMenu
	 */
	protected GuiSubitemTestObject contextMenu(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("contextMenu"), anchor, flags);
	}
	
	/**
	 * PropertiesForAs£º with default state.
	 *		.captionText : Properties for as
	 * 		.class : org.eclipse.swt.widgets.Shell
	 */
	protected TopLevelTestObject propertiesForAs() 
	{
		return new TopLevelTestObject(
                        getMappedTestObject("propertiesForAs"));
	}
	/**
	 * PropertiesForAs£º with specific test context and state.
	 *		.captionText : Properties for as
	 * 		.class : org.eclipse.swt.widgets.Shell
	 */
	protected TopLevelTestObject propertiesForAs(TestObject anchor, long flags) 
	{
		return new TopLevelTestObject(
                        getMappedTestObject("propertiesForAs"), anchor, flags);
	}
	
	/**
	 * Tree£º with default state.
	 *		.class : org.eclipse.swt.widgets.Tree
	 * 		.classIndex : 0
	 */
	protected ScrollGuiSubitemTestObject tree() 
	{
		return new ScrollGuiSubitemTestObject(
                        getMappedTestObject("tree"));
	}
	/**
	 * Tree£º with specific test context and state.
	 *		.class : org.eclipse.swt.widgets.Tree
	 * 		.classIndex : 0
	 */
	protected ScrollGuiSubitemTestObject tree(TestObject anchor, long flags) 
	{
		return new ScrollGuiSubitemTestObject(
                        getMappedTestObject("tree"), anchor, flags);
	}
	
	

	protected Script2Helper()
	{
		setScriptName("sample.Script2");
	}
	
}