// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.sample;
import sample.HelperSuperClass;
import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;

/**
 * Script Name   : <b>Script1</b><br>
 * Generated     : <b>2010/09/30 17:23:06</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows NT (unknown) x86 6.0 <br>
 * 
 * @since  ¾ÅÔÂ 30, 2010
 * @author think
 */
public abstract class Script1Helper extends sample.HelperSuperClass
{
	

	protected Script1Helper()
	{
		setScriptName("sample.Script1");
	}
	
}